/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/SplashScreenComponent`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/mainMenu` | `/mainMenu`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/objectsConfirm` | `/objectsConfirm`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/takePicture` | `/takePicture`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/SplashScreenComponent`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/mainMenu` | `/mainMenu`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/objectsConfirm` | `/objectsConfirm`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/takePicture` | `/takePicture`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/SplashScreenComponent${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/mainMenu${`?${string}` | `#${string}` | ''}` | `/mainMenu${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/objectsConfirm${`?${string}` | `#${string}` | ''}` | `/objectsConfirm${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/takePicture${`?${string}` | `#${string}` | ''}` | `/takePicture${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/SplashScreenComponent`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/mainMenu` | `/mainMenu`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/objectsConfirm` | `/objectsConfirm`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/takePicture` | `/takePicture`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
